import { colors, radius, shadow, spacing } from "@/theme/loveTheme";

export const theme = {
  colors: {
    background: colors.bg,
    backgroundSecondary: colors.bgSoft,
    backgroundLayer: colors.bgLayer,
    backgroundTertiary: colors.bgLavender,
    surface: colors.whiteGlass,
    surfaceSoft: colors.frosting,
    surfaceMuted: colors.bgSoft,
    text: colors.text,
    textMuted: colors.subtext,
    textPrimary: colors.text,
    textSecondary: colors.subtext,
    textSoft: colors.subtext,
    primary: colors.pink,
    primaryDark: colors.pink,
    accent: colors.pink,
    accentDeep: colors.pink,
    lavender: colors.purpleSoft,
    lavenderMist: colors.lavenderMist,
    dreamGradientStart: colors.pinkSoft,
    dreamGradientEnd: colors.purpleSoft,
    glowPink: colors.glow,
    pinkGlow: colors.pinkGlow,
    purpleGlow: colors.purpleGlow,
    card: colors.whiteGlass,
    cardStrong: colors.whiteSolid,
    border: colors.border,
    white: colors.whiteSolid,
    success: colors.success,
    danger: colors.danger,
    mapDot: colors.pink,
    overlay: colors.whiteGlass,
    shadow: colors.glow,
  },
  spacing: {
    xxs: 4,
    xs: spacing.xs,
    sm: spacing.sm,
    md: spacing.md,
    lg: spacing.lg,
    xl: spacing.xl,
    xxl: spacing.xxl,
  },
  radius: {
    sm: 16,
    md: radius.lg,
    lg: radius.xl,
    xl: radius.xxl,
    pill: radius.pill,
  },
  shadows: {
    soft: shadow.soft,
    dreamy: shadow.frosting,
    glow: shadow.glow,
  },
  typography: {
    hero: 34,
    section: 22,
    cardTitle: 18,
    body: 15,
    caption: 12,
  },
};
